2024-06-09 12:19:03,689 ERROR: Exception on /auth/login [GET] [in /home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py:825]
Traceback (most recent call last):
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 1455, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 869, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 867, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/app.py", line 852, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/alucard/python/kfu/minkin2024/app/auth/routes.py", line 30, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 152, in render_template
    return _render(app, template, context)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask/templating.py", line 133, in _render
    rv = template.render(context)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 1301, in render
    self.environment.handle_exception()
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/jinja2/environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "/home/alucard/python/kfu/minkin2024/app/templates/auth/login.html", line 2, in top-level template code
    {% import "bootstrap_wtf.html" as wtf %}
  File "/home/alucard/python/kfu/minkin2024/app/templates/base.html", line 55, in top-level template code
    {% block content %}{% endblock %}
  File "/home/alucard/python/kfu/minkin2024/app/templates/auth/login.html", line 5, in block 'content'
    <h1>{{ _('Sign In') }} {{ moment('2021-06-28T21:45:23+00:00').fromNow() }}</h1>
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_moment/__init__.py", line 229, in fromNow
    return self._render("fromNow", no_suffix=int(no_suffix),
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_moment/__init__.py", line 186, in _render
    t = self._timestamp_as_iso_8601(self.timestamp)
  File "/home/alucard/python/kfu/minkin2024/venv/lib/python3.10/site-packages/flask_moment/__init__.py", line 182, in _timestamp_as_iso_8601
    return timestamp.strftime('%Y-%m-%dT%H:%M:%S' + tz)
AttributeError: 'str' object has no attribute 'strftime'
2024-06-09 12:19:21,850 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:19:36,977 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:20:14,121 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:22:05,684 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:22:51,528 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:29:15,801 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:34:52,447 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:37:24,025 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:40:10,207 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:41:46,801 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:46:25,348 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-09 12:47:11,544 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
2024-06-11 13:32:09,188 INFO: minlin2024 [in /home/alucard/python/kfu/minkin2024/app/__init__.py:79]
